# Generated by Django 4.1 on 2024-05-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("author", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="age",
            field=models.PositiveIntegerField(),
        ),
    ]
